### ISSUE TITLE
[Question] What does module=default do?

### ISSUE THREAD

**Issue by MaoMaoCake** [prometheus-pve/prometheus-pve-exporter#108]
hi Ive setup the exporter with 
```pve.yml
default:
    user: prometheus@pve
    token_name: "prometheus"
    token_value: "token"
    verify_ssl: false
```
and the promethus job with
```
- job_name: 'pve'
    static_configs:
      - targets: 
        - 1.2.3.4 # Proxmox VE node.
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9221
```
when I curl with module in the url 
`http://127.0.0.1:9221/pve?module=default&target=1.2.3.4`
it fails with 500 
when i curl without module 
`http://127.0.0.1:9221/pve?target=1.2.3.4`
I get the metrics
