### ISSUE TITLE
how to use token credentials for two separte PVE nodes

### ISSUE THREAD

**Issue by braham2019** [prometheus-pve/prometheus-pve-exporter#236]
I have added a second Proxmox node to my setup. The first one is working fine using token authentication:

```
default:
    user: monitoring@pam
    token_name: "somename"
    token_value: "somevalue"
    verify_ssl: false
```

But the second one (they are not part of a cluster) has a different token secret (albeit the token_name and token_value are the same). 

As expected it gives an error when trying this.
```
proxmoxer.core.ResourceException: 401 Unauthorized: invalid token value! - {'errors': b''}
```
How can I pass those separate credentials to that particular node ? Is there a way to create an entry for that in pve.yml ?

**Comment by danpoltawski** [comment]
I was looking for the same thing, looks like you can do this with the module request param:

>Specify the module request parameter, to choose which module to use from the config file.

**Comment by xzivzs** [comment]
Hey guys, can you help me with that situation ? I've been monitoring my "main" Proxmox server for a long time now and I recently add another Proxmox server but it needs to be separate from my main for specific reason. Anyways, I would like to monitor this one as well but can't make it work . Do I need to create another "module" inside "pve.yml" ? 
```
default:
  user: monitor@pam
  token_name: "somename"
  token_value: "somevalue"
  verify_ssl: false

default2:
  user: monitor@pam
  token_name: "somename"
  token_value: "somevalue"
```
 I then specify the module's name inside prometheus.yml config but it doesn't work obviously :
```
  - job_name: 'somename'
    scrape_interval: 1m
    static_configs:
      - targets:
        - someip # Proxmox VE node 1

    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: someip:9221


  - job_name: 'somename'
    scrape_interval: 1m
    static_configs:
      - targets:
        - someip # Proxmox VE Arr Stack

    metrics_path: /pve
    params:
      module: [default2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: someip:9221
```
How can I do that ?

Cheers,
