### ISSUE TITLE
Limited set of kpis retrieve, high count of 

### ISSUE THREAD

**Issue by Concurser** [prometheus-pve/prometheus-pve-exporter#291]
I am getting only 5 pve kpis only when running the exporter. 

Also, the pve_request_errors_created{module="proxmox"} count is very high and keeps increasing. 

root@vmhost:/etc/promcurl --silent http://127.0.0.1:9221/metrics | grep pve
pve_collection_duration_seconds_count{module="proxmox"} 0.0
pve_collection_duration_seconds_sum{module="proxmox"} 0.0
pve_collection_duration_seconds_created{module="proxmox"} 1.7292670612843657e+09
pve_request_errors_total{module="proxmox"} 0.0
pve_request_errors_created{module="proxmox"} 1.7292670612843575e+09
root@vmhost:/etc/prometheus-pve-exporter#

**I made direct API json calls to the PVE service port and it´s answering fine.**

`root@vmhost:/etc/prometheus-pve-exporter# curl -k -b "PVEAuthCookie=PVE:pve-exporter@pve:67127D94::NC06ph8XGi3P7FWb9kFXBl0B9jcRhlf0ksZrq2fyE3eUeIbabldShNAMQKDo972AlsY2iIkEC+4YNtvYy2EQCw3987wQ/Ck+3varP64796v6Uc3xGr9vFeIvvC0PIPG/bzF2e4EMVLjJocTrMuUBJ7KSdiBy2l7Y6X3BBEQqx4C3f0sQK/pOhmTzeJK8QLK7Q3t94IYHq6JFP3xLAazKZGtgZXMLJRnvaVkg/CxwDWCVVuV+iJZOCfImqxJ9cGH28NmTZmlQHzjDrRKEIpbBUNz6Bf9DKaYRAtMW1HdtI670UsjkM+O2GdPMvdBCh6bQ2v5t4UNYKO1eMgPFtgv4bA==" -H "CSRFPreventionToken:tQJJxwAK2K5dRpti6D0jYav6tQXp5FhmAIaJ4hu/hpI" https://192.168.0.2:8006/api2/json/nodes
{"data":[{"mem":36188897280,"maxdisk":16268566528,"ssl_fingerprint":"3D:4E:A4:47:AB:98:FE:36:8B:00:52:90:11:FC:57:16:3B:0C:05:CB:D1:21:C2:E2:3F:D8:46:51:34:37:EA:82","type":"node","cpu":0.210004338932623,"maxmem":66677411840,"level":"","id":"node/vmhost","status":"online","uptime":162621,"maxcpu":16,"node":"vmhost","disk":5903441920}]}root@vmhost:/etc/prometheus-pve-exporter#
`

**The auditor role for my user was given as below:**

`
root@vmhost:~# pveum user permissions pve-exporter@pve
┌────────────────┬─────────────────────┐
│ ACL path       │ Permissions         │
╞════════════════╪═════════════════════╡
│ /              │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
│ /access        │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
│ /access/groups │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
│ /nodes         │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
│ /pool          │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
│ /sdn           │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
│ /storage       │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
│ /vms           │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
│ /vms/100       │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
└────────────────┴─────────────────────┘
`

Any ideas why my Grafana dashboard is not able to pull the metrics?

**Comment by znerol** [comment]
* Do you see any errors in the pve exporter logs?
* It looks like you configured `module: proxmox` in the prometheus scrape config. Did you actually configure a module named like this in [pve.yml](https://github.com/prometheus-pve/prometheus-pve-exporter/blob/main/pve.yml)? If you are using the config file shipping with this project, then the module names is `default`.

**Comment by Concurser** [comment]
Hello, I did force "proxmox" as the module name, it is a free choice, right?

```
root@vmhost:~# cat /etc/prometheus-pve-exporter/pve.yml
proxmox:
  user: pve-exporter@pve
  password: ************
  verify_ssl: false
```

```
root@vmhost:~# cat /etc/prometheus/prometheus.yml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["192.168.0.2:9090"]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.0.2:9100']

  - job_name: 'proxmox_exporter'
    static_configs:
      - targets: ['192.168.0.2:9221']
    #metrics_path: /pve
    params:
      module: [proxmox]
      cluster: ['1']
      node: ['1']

```

Where I can reach the pve exporter logs? The journalctl does not say much:

-- Boot 56c12071658249f09aaa6e9638a8be9e --
Oct 21 13:01:18 vmhost systemd[1]: Started prometheus-pve-exporter.service - Prometheus PVE Exporter.
Oct 21 13:01:18 vmhost pve_exporter[1623]: [2024-10-21 13:01:18 -0300] [1623] [INFO] Starting gunicorn 23.0.0
Oct 21 13:01:18 vmhost pve_exporter[1623]: [2024-10-21 13:01:18 -0300] [1623] [INFO] Listening at: http://[::]:9221 (1623)
Oct 21 13:01:18 vmhost pve_exporter[1623]: [2024-10-21 13:01:18 -0300] [1623] [INFO] Using worker: gthread
Oct 21 13:01:18 vmhost pve_exporter[1827]: [2024-10-21 13:01:18 -0300] [1827] [INFO] Booting worker with pid: 1827

After the module name change (matching the same on the pve-exporter and prometheus yml files) my error counter got stable, not increasing anymore (pve_request_errors_created), but I get return for only five pve_ metrics...

```

root@vmhost:~# curl --silent http://127.0.0.1:9221/metrics | grep pve
# HELP pve_collection_duration_seconds Duration of collections by the PVE exporter
# TYPE pve_collection_duration_seconds summary
pve_collection_duration_seconds_count{module="proxmox"} 0.0
pve_collection_duration_seconds_sum{module="proxmox"} 0.0
# HELP pve_collection_duration_seconds_created Duration of collections by the PVE exporter
# TYPE pve_collection_duration_seconds_created gauge
pve_collection_duration_seconds_created{module="proxmox"} 1.7295264784159312e+09
# HELP pve_request_errors_total Errors in requests to PVE exporter
# TYPE pve_request_errors_total counter
pve_request_errors_total{module="proxmox"} 0.0
# HELP pve_request_errors_created Errors in requests to PVE exporter
# TYPE pve_request_errors_created gauge
pve_request_errors_created{module="proxmox"} 1.7295264784159222e+09

```

Checking role assignment for my pve-exporter user:
```
root@vmhost:~# pveum user permissions pve-exporter@pve
┌────────────────┬─────────────────────┐
│ ACL path       │ Permissions         │
╞════════════════╪═════════════════════╡
│ /              │ Datastore.Audit (*) │
│                │ Mapping.Audit (*)   │
│                │ Pool.Audit (*)      │
│                │ SDN.Audit (*)       │
│                │ Sys.Audit (*)       │
│                │ VM.Audit (*)        │
├────────────────┼─────────────────────┤
```

**Comment by Concurser** [comment]
Doing the API call (1st getting the API ticket):

```
root@vmhost:~# curl -k -d "username=pve-exporter@pve&password=*******"   https://192.168.0.2:8006/api2/json/access/ticket
{"data":{"username":"pve-exporter@pve","cap":{"nodes":{"Sys.Audit":1},"sdn":{"SDN.Audit":1},"mapping":{"Mapping.Audit":1},"dc":{"Sys.Audit":1,"SDN.Audit":1},"vms":{"VM.Audit":1},"access":{},"storage":{"Datastore.Audit":1}},"ticket":"PVE:pve-exporter@pve:67170118::d9WlhtvI+t7s9GffJM2Kq5x1G79TwZheKXM5s6fAm4HD73KKnse6XspxMqQSfbQcFEt6rGYEI0/UhbJN6Pr6GbeKcHKZX+68lZtpYXc0eBQyMH8+IOaHpCHpKnarG9worHavEjXR2dQfupSg8VlTqeYM1BpQDqmfHI/1jySw5jLpPRoJVV+EkctN4Hf3ktI5YLaoBmtTz+WvKn5bJD+T9jOCB+v7UldaHYmsitjE/dME9I6//g6KvIKOAJDKQbiguH841VsTP+6xmixeEAN/it0EF6bEMTucz9tGGECqrszXKhWbZi2exqhIxaFRBk6mO1wkbZ/zKIdGdtoi45y7Aw==","CSRFPreventionToken":"67170118:bGG1Gtmqw57hfO5qgodUoZtZzeMBzZa5+SBmClaiccw"}}root@vmhost:~#
```

2nd calling the API:

```
root@vmhost:~# curl -k -b "PVEAuthCookie=PVE:pve-exporter@pve:67170118::d9WlhtvI+t7s9GffJM2Kq5x1G79TwZheKXM5s6fAm4HD73KKnse6XspxMqQSfbQcFEt6rGYEI0/UhbJN6Pr6GbeKcHKZX+68lZtpYXc0eBQyMH8+IOaHpCHpKnarG9worHavEjXR2dQfupSg8VlTqeYM1BpQDqmfHI/1jySw5jLpPRoJVV+EkctN4Hf3ktI5YLaoBmtTz+WvKn5bJD+T9jOCB+v7UldaHYmsitjE/dME9I6//g6KvIKOAJDKQbiguH841VsTP+6xmixeEAN/it0EF6bEMTucz9tGGECqrszXKhWbZi2exqhIxaFRBk6mO1wkbZ/zKIdGdtoi45y7Aw==" -H "CSRFPreventionToken:bGG1Gtmqw57hfO5qgodUoZtZzeMBzZa5+SBmClaiccw" https://192.168.0.2:8006/api2/json/nodes
{"data":[{"level":"","mem":39197126656,"uptime":34581,"id":"node/vmhost","maxmem":66678427648,"maxdisk":16268566528,"cpu":0.0749752352649827,"maxcpu":16,"disk":6043549696,"node":"vmhost","ssl_fingerprint":"3D:4E:A4:47:AB:98:FE:36:8B:00:52:90:11:FC:57:16:3B:0C:05:CB:D1:21:C2:E2:3F:D8:46:51:34:37:EA:82","type":"node","status":"online"}]}root@vmhost:~#
```

**Comment by znerol** [comment]
Please add `metrics_path: /pve` to the `proxmox_exporter` job in the prometheus config.

**Comment by Concurser** [comment]
If I add the metrics_path /pve to the proxmox_exporter nothing changes. Actually the service looks down:

```
up{instance="192.168.0.2:9090", job="prometheus"} | 1
up{instance="192.168.0.2:9221", job="proxmox_exporter"} | 0
up{instance="192.168.0.2:9100", job="node_exporter"} | 1
```

Looking at the http://prometheus_host:9090/targets?search= screen the endpoint is DOWN:

http://192.168.0.2:9221/pvecluster="1"module="proxmox"node="1" | DOWN | instance="192.168.0.2:9221"job="proxmox_exporter" | 11.793s ago | 1.940ms | server returned HTTP status 500 INTERNAL SERVER ERROR

But still, the pve_* data remains under the :9221/metrics with the same few 5 kpis I mentioned before (http://prometheus_host:9221/metrics)

This is my config file now...

```
root@vmhost:~# cat /etc/prometheus/prometheus.yml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["192.168.0.2:9090"]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.0.2:9100']

  - job_name: 'proxmox_exporter'
    static_configs:
      - targets: ['192.168.0.2:9221']
    metrics_path: /pve # this was commented before
    params:
      module: [proxmox]
      cluster: ['1']
      node: ['1']
root@vmhost:~#
```

Lastly, I have no errors on the journalctl logs for the prometheus-node-exporter.service and well for the prometheus.service ...

While I see that there is a need to tie prometheus with the /pve path somewhere, I think this is not going to change much since the actual /metrics path is returning few pve_ kpis .

```
root@vmhost:~# curl --silent http://127.0.0.1:9221/metrics | grep pve
# HELP pve_collection_duration_seconds Duration of collections by the PVE exporter
# TYPE pve_collection_duration_seconds summary
pve_collection_duration_seconds_count{module="proxmox"} 0.0
pve_collection_duration_seconds_sum{module="proxmox"} 0.0
# HELP pve_collection_duration_seconds_created Duration of collections by the PVE exporter
# TYPE pve_collection_duration_seconds_created gauge
pve_collection_duration_seconds_created{module="proxmox"} 1.7295264784159312e+09
# HELP pve_request_errors_total Errors in requests to PVE exporter
# TYPE pve_request_errors_total counter
pve_request_errors_total{module="proxmox"} 72.0
# HELP pve_request_errors_created Errors in requests to PVE exporter
# TYPE pve_request_errors_created gauge
pve_request_errors_created{module="proxmox"} 1.7295264784159222e+09
```
