### ISSUE TITLE
Allow scrapping multiple targets in 1 request

### ISSUE THREAD

**Issue by isc30** [prometheus-pve/prometheus-pve-exporter#328]
Something like `/pve?target=192.168.1.2&target=192.168.1.3` would be very helpful to simplify kubernetes ServiceMonitors:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pve-monitor
spec:
  endpoints:
    - interval: 10s
      path: /pve
      port: http
      params:
        module: ['default']
        cluster: ['1']
        node: ['1']
        target: ['192.168.1.2','192.168.1.3']
      relabelings:
        - targetLabel: instance
          replacement: prometheus-pve-exporter
```

**Comment by znerol** [comment]
Prometheus has parallel scraping built-in, there is no need to implement that in PVE Exporter. I do not use kubernetes ServiceMonitors, but from the looks of it, you could just repeat the endpoint definition. I.e.:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pve-monitor
spec:
  endpoints:
    - interval: 10s
      path: /pve
      port: http
      params:
        module: ['default']
        cluster: ['1']
        node: ['1']
        target: ['192.168.1.2']
      relabelings:
        - targetLabel: instance
          replacement: prometheus-pve-exporter
    - interval: 10s
      path: /pve
      port: http
      params:
        module: ['default']
        cluster: ['1']
        node: ['1']
        target: [''192.168.1.3']
      relabelings:
        - targetLabel: instance
          replacement: prometheus-pve-exporter
```
