### ISSUE TITLE
Collect from node only information about node's VMs/CTs/etc

### ISSUE THREAD

**Issue by maelstrom256** [prometheus-pve/prometheus-pve-exporter#54]
Currently, it collects data from every cluster node full set of cluster-wide metrics.

If you have twelve nodes in one cluster, you'll get a dozen of identical data.
It's an extremely duping of data and excessive resources waste.

**Comment by znerol** [comment]
There are multiple strategies to mitigate this problem. From the top of my head:
1. Setup a round robin DNS entry for scraping. I.e. instead of configuring 12 targets in your prometheus config, only specify the round robin DNS record containing all the pve nodes you want to scrape.
2. Only collect metrics from a subset of those nodes. For best results select nodes which are never down at the same time.

In the second case you might want to relabel the collected metrics after scraping and replace the instance label with something which does not change between machines.

The simplest relabel config is the following;

```yaml
    metric_relabel_configs:
      - action: replace
        target_label: instance
        replacement: mycluster.example.com
      - action: labeldrop
        regex: exported_instance
```

It will force `instance=mycluster.example.com` and drop `exported_instance` completely.
