### ISSUE TITLE
Proxmox Host on port 443 instead of 8006

### ISSUE THREAD

**Issue by logopk** [prometheus-pve/prometheus-pve-exporter#96]
Hi,

Is there a way to configure the exporter to query on port 443 via nginx instead of 8006?

I have to keep 8006 open for the remote query via /etc/default/pveproxy and cannot close it down.

Thanks.

**Comment by znerol** [comment]
Prometheus PVE Exporter uses [https://github.com/proxmoxer/proxmoxer](proxmoxer) under the hood. It looks like there are two ways to specify a port in the [HTTPS Backend](https://github.com/proxmoxer/proxmoxer/blob/fc5ead8dc1d28249543dba907f04bccb8289caf3/proxmoxer/backends/https.py#L217-L223):

```python
class Backend(object):
    def __init__(self, host, user=None, password=None, otp=None, port=None,
                 verify_ssl=True, mode='json', timeout=5, auth_token=None,
                 csrf_token=None, token_name=None, token_value=None, service='PVE'):
        if ':' in host:
            host, host_port = host.split(':')
            port = host_port if host_port.isdigit() else port
```

Either specify `port` alongside `user` and `password` in `pve.yml` or supply `host:port` as the `target` param in `prometheus` scraper config.

Example for pve.yml:

```yml

default:
  user: prometheus@pve
  password: sEcr3T!
  port: 443
```

Example for prometheus config:

```yml
scrape_configs:
  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.1.2:443  # Proxmox VE node listening on HTTPS port.
        - 192.168.1.3:443  # Proxmox VE node listening on HTTPS port.
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9221  # PVE exporter.
```
